---
title: "FCC's Form 477"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{FCC's Form 477"}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## FCC's Form 477

Simplifying access to data is usually a matters of opinion: what data should we kept, what should be discarded?

For effectif data analysis it is important to communicate those decisions and provide the data's story. 

### Short introduction

FCC was reporting on Form 477 about Fixed Broadband deployement. 
Broadband providers were required to fill it: 

> **All** facilities-based broadband providers are required to file data with the FCC twice a year (Form 477) on where they offer Internet access service at speeds exceeding 200 kbps in at least one direction.  
> **Fixed** providers file lists of census blocks in which they can or do offer service to at least one location, with additional information about the service.

Source: https://www.fcc.gov/general/broadband-deployment-data-fcc-form-477

The census block mentioned are from **US census blocks** and from the **2010 vintage**.
Water only census blocks are also removed. 

Every row in this dataset is matching a specific services provided by an ISP in a census block. 
Hence an ISP can provides multiple services, for example different technologies or diffrent speeds in a census block. 

The time period covered goes from December 2014 and then have an update in June and December for every next year until december 2021.  

<hr>
**NOTE**
A provider is just required to tell if he provides a specific services in a block and is not required to provide how much in that block he is covering within it.   
<hr>

### License and attribution 

> Broadband data from FCC Form 477, and data from the U.S. Census Bureau that are presented on this site are offered free and not subject to copyright restriction. 

FCC is asking for proper credit to be given: 

* Source data: FCC Form 477

If you are using these data please follow those simple guidelines.

Source: https://broadband477map.fcc.gov/#/about

## Our opinionated version: 

From 477 data was released in multiple versions for some but not all release.
We took the decision to only use and ingest the last release of each version. 
We are assuming here that those versions are more consistant and only selecting teh last one will help homogeneize this dataset.

We decided that satellite data were less important hence we focused in *Fixed without satellite* data.

Not keeping variables: .  

Our opinionated version is maybe supbotimal for you and maybe you need to look at our implementation making sure that our process is reliable.
For that we are providing all the code used to generated this data set here: `data-raw/f477.R`   


### Data dictionary 



